---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flux-crd
  labels:
    app: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux:crd
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: flux
