---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux:crd
  labels:
    app: flux
rules:
  # CRDs are defined at the cluster scope and Flux will complain if it cannot list or watch these
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - watch
