apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    password: AgAJNAo3g6sdshZZsvRa+M+L1sb8EbzisZW8Wvf25GkXVFB6l5uL6Jx3nzEKUeWZcn7IvG5iOaPNqvr5sj+h6m2P758HbxJo/Ch3vM+pB+XylYGuEUkRl11jIddro1kHe0kjg0EJ0wK/d/vpk8LZ2GEHLnVeBW4AFGIWDpcJhalNF2r6Fz1Rp2AxKmuq10HDLRPlRuvnM5mrM/IMhnfT5up0nHRh2AeqVl4i+h/IoFUX6y1LEUkTUw0WStd2RFEvLPuAkVhm0eJNrx3t/VPXVxdFakWrIX1fgRC/II5eVuN1jUFT/GZdccFr/oWFNOKejtPltcL56kzYDFO0y0BFFmT7uQu7G/SwLW4vZnfORZcEJG4H1m1eQxVX/fviQcE/lQa+Nvvdaa+ViklFxn+3LmzEjVyVlkI8R2xILgpCDgYfEIOJOD4o6DzCkqsxK33yIUDhZHYlCCuHfrDDvDCb+o7u4SGC1XBQ446+qJUWO9Tx5VjjX/ZcqCx9L4qw/hR/hfE17E6YWt726GGxAl2og4tiVhK87TElIuyLC/IFFUPTRyUZwRSrH8B7ukIDSqqe0XOTzo+vOSJlpAiXNnmkAfbqjF/TstiTOcmSGbFdIeLKADfEuJoZkI4icJFKB5BNjAOcW8jVfOY4gUQvUC7JVJ7cYGdCo5QM9F5yG1udqaUx+rDOe3Utv0cx6GgQ7Gkr3biiCPNCkw==
    user: AgC56nO4G9fCpTNvrhC+b0r/t8/JqMEJ5MvR9euMAvW5JZgZqGUo+Y0ftBOSYYgrUbCibQm26HYSVlZCL1RxNYv321Xt4ts7RXXi5CL+66LYOquqgcK+OWFrasKd9YLHilUZaqS9jJdz950KsWFc3j15Yf259q+U3MniXOP8uH87YlSuVaL820Ym68r5LlwbomGPm8AAQG6moQ5RB3KIV+9KOVzfrQlENh0FtAR7Q/vntSQUvMJx4IXfQBWAZy6+2uz51lH9fFnb0L4mY+d85pAdwyCVX1T1Qj3t8fqo8wBXl23hKo+WCHnYq20iEdVyvoNS5kzVM7X+5xWmsqOjt+QThGjeTzM0Xn/XukiM2UwMA9kdBCSWP8jFS+kvHYu4pTffYTB1E0MrtjK1ia7bm3AjaOvaf/QRzg9VXJX9AgIJhuTJxq/6/jlR8Pr46ZDc7NSY+ktrJQhfyYx2FqWutndSsnYpEvZT+68b96QXvdR2IM8AGCqLxwTad/OpBNKgIwG5NS9iCaVF++nLcF9Xh9Jr3yhlluCqVoedlQ48/m3RKY5tmR1ZXfEaGPeXJ5kgXmnlOBxfCT3tyWBhQ4tVIlhYwVuKSDVPURO73brM3S2QNUhKqWi1z5QQbNHK1sDMEwBpoiVac/2VtZUuSI3LJr3zJk4uI5s+tnWo6j3xOwWJabc13OJJbmh14EOkvVNQrNUzmn1QQA==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: demo

