apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: {{ .Values.image }} 
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: basic-auth
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: basic-auth
              key: password
        ports:
        - containerPort: 80
