apiVersion: v1
kind: Service
metadata:
  name: webapp1-service
  namespace: demo
spec:
  selector:
    app: webapp1-service
  ports:
  - protocol: TCP
    port: {{ .Values.service.port}}
    targetPort: 80
  type: ClusterIP